import "./globals.css";
import type { Metadata } from "next";
import { Inter, VT323, Blinker } from "next/font/google";
import { dir } from "i18next";

import { Background } from "@/components/background";

const languages = ["pl", "en"];

const inter = Inter({ subsets: ["latin"] });
const vt323 = VT323({
  variable: "--VT-font",
  weight: ["400"],
  subsets: ["latin"],
});
const blinker = Blinker({
  variable: "--blinker-font",
  weight: ["400", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Ostatni dzwonek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: string };
}) {
  return (
    <html
      lang={lng}
      dir={dir(lng)}
      className={`${vt323.variable} ${blinker.variable}`}
    >
      <body className={inter.className}>
        <Background />

        {children}
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
