import "./globals.css";
import type { Metadata } from "next";
import { Inter, VT323, Blinker } from "next/font/google";
import { dir } from "i18next";

import { Background } from "@/src/components/background";
import { Navbar } from "@/src/components/Navbar";

const languages = ["pl", "en"];

const inter = Inter({ subsets: ["latin"] });
const vt323 = VT323({
  variable: "--VT-font",
  weight: ["400"],
  subsets: ["latin"],
});
const blinker = Blinker({
  variable: "--blinker-font",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Ostatni dzwonek",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lng },
  searchParams,
}: {
  children: React.ReactNode;
  params: { lng: string };
  searchParams: URLSearchParams;
}) {
  return (
    <html
      lang={lng}
      dir={dir(lng)}
      className={`${vt323.variable} ${blinker.variable}`}
    >
      <body className={inter.className}>
        <Navbar lng={lng} />
        <Background />

        {children}
        <footer className="absolute bottom-0 left-0 w-full py-[1rem] h-[4rem] text-black text-[1.6rem] text-center">
          Copyright &copy; 2023 AEXOL
          <span className="hidden md:inline-block">
            , Sp. z o.o. Wszelkie prawa zastrzeżone.
          </span>
        </footer>
      </body>
    </html>
  );
}

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}
